name: sqlite_drift_demo
description: Demo SQLite vs Drift
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter

  # SQLite thuần
  sqflite: ^2.3.0
  path: ^1.8.3

  # Drift ORM
  drift: ^2.14.0
  drift_flutter: ^0.1.0

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Drift code generation
  drift_dev: ^2.14.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true